apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dotnet-api
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: dotnet-api
    spec:
      containers:
      - name: dotnet-api
        image: dockerregistryacr.azurecr.io/dotnet-api:___BuildNumber___ 
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
      imagePullSecrets:
      - name: dm-aks-common-registrykey
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-api
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: dotnet-api
